name: reference_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  auto_route: ^7.8.4
  build_runner: ^2.4.8
  cloud_firestore: ^4.14.0
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

dev_dependencies:
  auto_route_generator: ^7.3.2
  custom_lint: ^0.6.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  pedantic_mono: ^1.24.0+1
  riverpod_lint: ^2.3.9

flutter:
  uses-material-design: true
