// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWvj7UbQ7RNUT3mfv-C-OliyhNx2--uoU',
    appId: '1:387997892914:web:9dd13498596933e441172b',
    messagingSenderId: '387997892914',
    projectId: 'reference-app-47de9',
    authDomain: 'reference-app-47de9.firebaseapp.com',
    storageBucket: 'reference-app-47de9.appspot.com',
    measurementId: 'G-Y44W7YXVWG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANykK5ERDQXyZu2nFYMponOw2d-J_JH1I',
    appId: '1:387997892914:android:47d32a0dbf47e68541172b',
    messagingSenderId: '387997892914',
    projectId: 'reference-app-47de9',
    storageBucket: 'reference-app-47de9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk7GW51AxCxc2Fk_cz-lHz6XI5sxzQm_U',
    appId: '1:387997892914:ios:242f562252dbf5db41172b',
    messagingSenderId: '387997892914',
    projectId: 'reference-app-47de9',
    storageBucket: 'reference-app-47de9.appspot.com',
    iosBundleId: 'com.example.referenceApp.RunnerTests',
  );
}
